#!/bin/bash
# Build script

CC=cc
DEBUG="-g"
STRIP="-s"
FLAGS="-Ofast -Wall -Wextra -march=native"
LINK="-lm"
PROGRAM="ne7"

file_ok() {
    [ -f "$1" ] && return 0 || return 1
}

main() {
    [ -z "$1" ] && {
        echo "Error: No build command was provided"
        exit 1
    }

    case "$1" in
        debug)
            ${CC} ${DEBUG} ${FLAGS} ${PROGRAM}.c ${LINK} -o ${PROGRAM}
            ;;
        release)
            ${CC} ${STRIP} ${FLAGS} ${PROGRAM}.c ${LINK} -o ${PROGRAM}
            ;;
        clean)
            rm ne7
            ;;
        test)
            file_ok ./${PROGRAM} && ./${PROGRAM} --text "Hello world ${IFS}"
            ;;
        *)
            echo "Error: Unknown command $1"
            ;;
    esac 
}

main "$1"
